In [1]:
import numpy as np
import torch

In [2]:
# create a vector
nv1 = np.array([1, 2, 3, 4])
nv2 = np.array([0, 1, 0, -1])

# dot product via function
print(np.dot(nv1, nv2))
print(nv1 * nv2)
# dot product via computation
print(np.sum(nv1*nv2))

-2
[ 0  2  0 -4]
-2


In [3]:
# Dot product in 2D

nv1 = np.array([[0, 3, 2], [-3, -3, 1], [1, 0, 2]])
nv2 = np.array([[1, 0, 6], [2, -1, 0], [5, 1, 4]])

np.dot(nv1, nv2)  # matrix multiplication

array([[ 16,  -1,   8],
       [ -4,   4, -14],
       [ 11,   2,  14]])

In [4]:
nv1 * nv2

array([[ 0,  0, 12],
       [-6,  3,  0],
       [ 5,  0,  8]])

In [5]:
np.sum(nv1 * nv2)

np.int64(22)

In [6]:
# create a vector
tv1 = torch.tensor([1, 2, 3, 4])
tv2 = torch.tensor([0, 1, 0, -1])

# dot product via function
print(torch.dot(tv1, tv2))

# dot product via computation
print(torch.sum(tv1*tv2))

tensor(-2)
tensor(-2)


In [7]:
tv1 = torch.tensor([[0, 3, 2], [-3, -3, 1], [1, 0, 2]])
tv2 = torch.tensor([[1, 0, 6], [2, -1, 0], [5, 1, 4]])

try:
    print(torch.dot(tv1, tv2))
except Exception as e:
    print(f'Error: {e}')

Error: 1D tensors expected, but got 2D and 2D tensors


In [8]:
tv1*tv2

tensor([[ 0,  0, 12],
        [-6,  3,  0],
        [ 5,  0,  8]])

In [9]:
print(torch.sum(tv1*tv2))

tensor(22)
