In [127]:
import numpy as np
import torch

In [128]:
A = np.array([
    [1, 3, 2],
    [1, 1, 1],
    [1, 0, 2]
])
B = np.array([
    [1, 2, 6],
    [2, 7, 0],
    [5, 1, 4]
])

A@B

array([[17, 25, 14],
       [ 8, 10, 10],
       [11,  4, 14]])

In [129]:
B@A

array([[ 9,  5, 16],
       [ 9, 13, 11],
       [10, 16, 19]])

In [130]:
A = np.random.randn(3, 4)
A

array([[-1.12388555, -1.08898634, -1.98745375,  0.19419686],
       [ 0.2929208 ,  0.66391981, -0.46155944, -0.42313374],
       [ 0.80789704,  0.53825832,  0.87645237, -0.30680579]])

In [131]:
np.round(A, 2)

array([[-1.12, -1.09, -1.99,  0.19],
       [ 0.29,  0.66, -0.46, -0.42],
       [ 0.81,  0.54,  0.88, -0.31]])

In [132]:
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
np.round(A@B, 2)

array([[-1.1 , -0.05, -1.12,  0.48,  2.55],
       [-0.11,  1.91, -0.32, -0.53,  1.24],
       [ 1.24,  0.88,  0.03, -1.04,  0.99]])

In [133]:
try:
    np.round(B@A, 2)
except Exception as e:
    print(f'Error: {e}')

Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)


In [134]:
C = np.random.randn(3, 7)
print(np.round(C.T@A, 2))

[[ 1.76 -0.2   1.91 -1.52]
 [ 5.24 -3.57 -0.49 -1.77]
 [ 0.93  0.7  -0.53  0.13]
 [ 0.83 -1.98  0.02 -0.56]
 [ 1.24 -0.62 -0.48 -0.19]
 [ 2.41 -1.46  1.13 -1.49]
 [-0.87  1.33  1.67 -0.42]]


In [135]:
A = np.random.randn(3, 4)
A.dtype

dtype('float64')

In [136]:
A = torch.randn(3, 4)
A.dtype

torch.float32

In [137]:
A = torch.randn(3, 4)
B = torch.randn(4, 5)


print(torch.round(A @ B, decimals=2))

tensor([[-0.7200, -3.6400, -0.3100,  0.0600, -0.7100],
        [-0.0700,  2.0300,  1.1800, -1.1800,  0.2300],
        [ 0.2000, -2.9200,  1.4200, -1.7700, -1.5300]])


In [138]:
print(np.round(A@B, 2))  # np.round works for tensor

tensor([[-0.7200, -3.6400, -0.3100,  0.0600, -0.7100],
        [-0.0700,  2.0300,  1.1800, -1.1800,  0.2300],
        [ 0.2000, -2.9200,  1.4200, -1.7700, -1.5300]])


In [139]:
C1 = np.random.randn(4, 7)
print(np.round(A.numpy()@C1, 2))

[[ 2.49  0.48  1.62  1.85  0.28 -0.62  0.83]
 [-0.89  0.71  1.45 -2.33  0.31 -0.78  1.36]
 [ 1.58 -0.74  2.73  1.82  0.83 -2.85  0.11]]


In [140]:
C2 = torch.tensor(C1, dtype=torch.float)
# C1 is float64/double, for performing matmul with A which is float32/float, we need to typecast
print(np.round(A@C2, 2))

tensor([[ 2.4900,  0.4800,  1.6200,  1.8500,  0.2800, -0.6200,  0.8300],
        [-0.8900,  0.7100,  1.4500, -2.3300,  0.3100, -0.7800,  1.3600],
        [ 1.5800, -0.7400,  2.7300,  1.8200,  0.8300, -2.8500,  0.1100]])


In [141]:
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
print(np.round(A@B, 2))
# torch.round doesn't works on ndarray, we need to convert to tensor
print(torch.round(torch.tensor(A@B), decimals=2))

[[-0.57  2.23  1.86  1.35  1.36]
 [-2.29 -0.95  3.76  0.29 -0.  ]
 [-1.81  0.37 -0.19  0.28 -1.74]]
tensor([[-0.5700,  2.2300,  1.8600,  1.3500,  1.3600],
        [-2.2900, -0.9500,  3.7600,  0.2900, -0.0000],
        [-1.8100,  0.3700, -0.1900,  0.2800, -1.7400]], dtype=torch.float64)
